// Generated by MARIGOLD-BATCH-APP (5-field outreach batch).
import type { MarigoldConfig } from "./config";

export const BUSINESS: MarigoldConfig = {
  "businessName": "Fauna Cafe",
  "location": "",
  "palette": "marigold-green",
  "fontSet": "fraunces-dmsans",
  "heroImage": "C:\\Users\\steve\\Downloads\\cafe-heros\\fortuna-cafe-edinburgh.jpg",
  "aboutQuote": "We opened Fauna Cafe to be the kind of place we missed — somewhere warm, where the bread is real, the coffee is strong and nobody is in a rush.",
  "aboutAttribution": "— The owners",
  "phone": "0131 000 0000",
  "email": "Hi@faunacafe.co.uk",
  "address": [
    "19a Queensferry Street",
    "Edinburgh"
  ]
};
